# Generated by Django 5.2.5 on 2025-08-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_country_profile_mobile_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
