# Generated by Django 5.2.5 on 2025-08-26 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=250)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('job_discription', models.TextField()),
                ('category', models.CharField(choices=[('Web Development', 'Web Development'), ('C++', 'C++'), ('Machine Learning', 'Machine Learning'), ('Data Science', 'Data Science')], default='Web Development', max_length=50)),
                ('num_questions', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('score', models.CharField(max_length=50)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.session')),
            ],
        ),
    ]
