# Generated by Django 5.2.5 on 2025-08-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='num_questions',
            field=models.IntegerField(),
        ),
    ]
