# Generated by Django 5.2.5 on 2025-08-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_alter_questions_session_alter_session_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='feedback',
            field=models.CharField(default='', max_length=700),
        ),
    ]
