# Generated by Django 5.2.5 on 2025-08-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_questions_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
