# Generated by Django 5.2.5 on 2025-09-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_alter_questions_answer_alter_questions_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
